### ISSUE TITLE
Feature request: restart Kakata on unlock event, kill on lock

### ISSUE THREAD

**Issue by bogorad** [reidprichard/window_tools#6]
Windows ignores Kanata when locked anyway.

**Comment by reidprichard** [comment]
If I'm understanding, you want _kanata_helper_daemon_ to kill and restart Kanata itself?
I think that's fairly outside this project's scope. You should be able to implement that with Task Scheduler, or if not then [kanata-tray](https://github.com/rszyma/kanata-tray) would be a more suitable project, as its goal is to manage Kanata. Feel free to reopen if I misunderstood what you're looking for.
